apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: nginx-app
  name: nginx-app 
  namespace: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: nginx
    repoURL: https://github.com/DaanWillems/k3s-deployments
    targetRevision: HEAD
